# Generated by Django 4.2.11 on 2026-03-07 13:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('feedback_type', models.CharField(choices=[('bug', 'Bug'), ('suggestion', 'Suggestion'), ('question', 'Question'), ('other', 'Other')], default='suggestion', max_length=15)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='new', max_length=15)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='checker.user')),
            ],
            options={
                'db_table': 'user_feedback',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScanRequest',
            fields=[
                ('input_id', models.AutoField(primary_key=True, serialize=False)),
                ('input_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('face', 'Face')], max_length=10)),
                ('input_value', models.CharField(blank=True, max_length=255, null=True)),
                ('face_path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verifying', 'Verifying'), ('verified', 'Verified'), ('scanning', 'Scanning'), ('completed', 'Completed'), ('not_found', 'Not Found'), ('error', 'Error')], default='pending', max_length=15)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='checker.user')),
            ],
            options={
                'db_table': 'scan_requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('result_count', models.IntegerField(default=0)),
                ('highest_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('report_name', models.CharField(max_length=25)),
                ('report_format', models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML'), ('json', 'JSON')], default='pdf', max_length=10)),
                ('report_path', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('input', models.ForeignKey(db_column='input_id', on_delete=django.db.models.deletion.CASCADE, to='checker.scanrequest')),
            ],
            options={
                'db_table': 'reports',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContinuousMonitoring',
            fields=[
                ('monitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('input_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('face', 'Face')], max_length=10)),
                ('input_value', models.CharField(blank=True, max_length=255, null=True)),
                ('face_path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='active', max_length=10)),
                ('frequency_minutes', models.IntegerField(default=60)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='checker.user')),
            ],
            options={
                'db_table': 'continuous_monitoring',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BreachResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=255)),
                ('site_url', models.CharField(max_length=1000)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('leaked_data', models.TextField()),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('input', models.ForeignKey(db_column='input_id', on_delete=django.db.models.deletion.CASCADE, to='checker.scanrequest')),
            ],
            options={
                'db_table': 'breach_results',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('in_app', 'In App'), ('email', 'Email')], default='in_app', max_length=10)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('read', 'Read')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('monitor', models.ForeignKey(blank=True, db_column='monitor_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='checker.continuousmonitoring')),
                ('result', models.ForeignKey(blank=True, db_column='result_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='checker.breachresult')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='checker.user')),
            ],
            options={
                'db_table': 'alerts',
                'managed': True,
            },
        ),
    ]
