# Generated by Django 4.2.11 on 2026-03-26 16:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersInputLogs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('search_type', models.CharField(max_length=20)),
                ('search_query', models.CharField(max_length=255)),
                ('user_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='checker.user')),
            ],
            options={
                'db_table': 'users_input_logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsernameSearchResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('platform_name', models.CharField(max_length=100)),
                ('profile_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='checker.user')),
                ('log', models.ForeignKey(db_column='log_id', on_delete=django.db.models.deletion.CASCADE, to='checker.usersinputlogs')),
            ],
            options={
                'db_table': 'username_search_results',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PhoneSearchResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('carrier', models.CharField(blank=True, max_length=100, null=True)),
                ('line_type', models.CharField(blank=True, max_length=50, null=True)),
                ('spam_score', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='checker.user')),
                ('log', models.ForeignKey(db_column='log_id', on_delete=django.db.models.deletion.CASCADE, to='checker.usersinputlogs')),
            ],
            options={
                'db_table': 'phone_search_results',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmailSearchResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('is_deliverable', models.BooleanField(default=False)),
                ('is_disposable', models.BooleanField(default=False)),
                ('breach_count', models.IntegerField(default=0)),
                ('breach_sources', models.JSONField(blank=True, null=True)),
                ('domain_age_days', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='checker.user')),
                ('log', models.ForeignKey(db_column='log_id', on_delete=django.db.models.deletion.CASCADE, to='checker.usersinputlogs')),
            ],
            options={
                'db_table': 'email_search_results',
                'managed': True,
            },
        ),
    ]
