# Generated by Django 5.2.13 on 2026-04-11 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        # Temporarily disabling 'managed = False' for tests to allow table creation
        # migrations.AlterModelOptions(
        #     name='emailsearchresults',
        #     options={'managed': False},
        # ),
        # ... and others
    ]
